management:
  server:
    servlet:
      context-path: /actuator
  health:
    mail:
      enabled: false

mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml
spring:
  datasource:
    dynamic:
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/xxl_job?nullCatalogMeansCurrent=true&nullDatabaseMeansCurrent=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
          username: root
          password: ENC(OaXuTbJoWUDnWF4laulbExgQplXff/01HJLvMGmxnBfk5OULxo1rjPuFTMxemBph)
  mail:
    host: ${XXL_JOB_MAIL_HOST:}
    port: ${XXL_JOB_MAIL_PORT:25}
    username: ${XXL_JOB_MAIL_USERNAME:}
    from: ${XXL_JOB_MAIL_FROM:}
    password: ${XXL_JOB_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

xxl:
  job:
    accessToken: ${XXL_JOB_ACCESS_TOKEN:default_token}
    i18n: ${XXL_JOB_I18N:zh_CN}
    triggerpool:
      fast:
        max: ${XXL_JOB_TRIGGERPOOL_FAST_MAX:200}
      slow:
        max: ${XXL_JOB_TRIGGERPOOL_SLOW_MAX:100}
    logretentiondays: ${XXL_JOB_LOG_RETENTION_DAYS:30}

user:
  password:
    lockTime: 10
    maxRetryCount: 5