server:
  port: 9002

spring:
  application:
    name: snail-camunda
#  profiles:
#    active: @profiles.active@
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/camunda?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
  # Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 
    timeout: 10s
#  cloud:
#    nacos:
#      # nacos 服务地址
#      server-addr: @nacos.server@
#      username: @nacos.username@
#      password: @nacos.password@
#      discovery:
#        # 注册组
#        group: @nacos.discovery.group@
#        namespace: ${spring.profiles.active}
#      config:
#        # 配置组
#        group: @nacos.config.group@
#        namespace: ${spring.profiles.active}
  # Camunda配置
camunda:
  bpm:
    database:
      type: mysql #可改成 mysql
      schema-update: true
    auto-deployment-enabled: false # 自动部署 resources 下的 bpmn文件
    admin-user:
      id: demo
      password: demo

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.snail.camunda.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0


# Dubbo配置
#dubbo:
#  application:
#    name: ${spring.application.name}
#  protocol:
#    name: dubbo
#    port: -1
#  registry:
#    address: nacos://127.0.0.1:8848