server:
  port: 9001

spring:
  application:
    name: snail-sys
  profiles:
    active: dev
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/snail_sys?nullCatalogMeansCurrent=true&nullDatabaseMeansCurrent=true&useSSL=false&characterEncoding=utf8
          username: root
          password: 123456
  # Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 10s
# 日志配置
logging:
  level:
    org.springframework: info
#    org.apache.dubbo: warn
#    com.alibaba.nacos: warn
#  config: classpath:logback-plus.xml
# MyBatisPlus配置
# https://baomidou.com/config/
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

user:
  password:
    lockTime: 10
    maxRetryCount: 5