server:
  port: 9002
  servlet:
    context-path: /xxl-job-admin

spring:
  application:
    name: snail-job-admin
  profiles:
    active: ${PROFILES_ACTIVE:dev}
  config:
    import:
      - optional:nacos:snail-global.yml?group=${NACOS_CONFIG_GROUP:DEFAULT_GROUP}&refreshEnabled=true
      - optional:nacos:datasource.yml?group=${NACOS_CONFIG_GROUP:DEFAULT_GROUP}&refreshEnabled=true
      - optional:nacos:snail-job-admin.yml?group=${NACOS_CONFIG_GROUP:DEFAULT_GROUP}&refreshEnabled=true
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        group: ${NACOS_DISCOVERY_GROUP:DEFAULT_GROUP}
        namespace: ${spring.profiles.active}
      config:
        group: ${NACOS_CONFIG_GROUP:DEFAULT_GROUP}
        namespace: ${spring.profiles.active}

jasypt:
  encryptor:
    password: ${jasypt.encryptor.password:${JASYPT_ENCRYPTOR_PASSWORD:}}
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    string-output-type: base64

management:
  endpoints:
    web:
      exposure:
        include: health,info
